// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnrokTransaction struct {
	ID                        pgtype.UUID    `json:"id"`
	TransactionID             pgtype.Text    `json:"transaction_id"`
	CustomerID                pgtype.Text    `json:"customer_id"`
	CustomerName              pgtype.Text    `json:"customer_name"`
	OverallVatIDStatus        pgtype.Text    `json:"overall_vat_id_status"`
	ValidVatIds               pgtype.Text    `json:"valid_vat_ids"`
	OtherVatIds               pgtype.Text    `json:"other_vat_ids"`
	InvoiceDate               pgtype.Date    `json:"invoice_date"`
	TaxDate                   pgtype.Date    `json:"tax_date"`
	TransactionCurrency       pgtype.Text    `json:"transaction_currency"`
	SalesAmount               pgtype.Numeric `json:"sales_amount"`
	ExemptReason              pgtype.Text    `json:"exempt_reason"`
	TaxAmount                 pgtype.Numeric `json:"tax_amount"`
	InvoiceAmount             pgtype.Numeric `json:"invoice_amount"`
	Void                      pgtype.Bool    `json:"void"`
	CustomerAddressLine1      pgtype.Text    `json:"customer_address_line_1"`
	CustomerAddressCity       pgtype.Text    `json:"customer_address_city"`
	CustomerAddressRegion     pgtype.Text    `json:"customer_address_region"`
	CustomerAddressPostalCode pgtype.Text    `json:"customer_address_postal_code"`
	CustomerAddressCountry    pgtype.Text    `json:"customer_address_country"`
	CustomerCountryCode       pgtype.Text    `json:"customer_country_code"`
	Jurisdictions             pgtype.Text    `json:"jurisdictions"`
	JurisdictionIds           pgtype.Text    `json:"jurisdiction_ids"`
	ReturnIds                 pgtype.Text    `json:"return_ids"`
}

type CsvUpload struct {
	Name       string           `json:"name"`
	Action     string           `json:"action"`
	UploadedAt pgtype.Timestamp `json:"uploaded_at"`
}

type NsInvoiceSalesTaxItem struct {
	ID                      pgtype.UUID    `json:"id"`
	Type                    pgtype.Text    `json:"type"`
	Date                    pgtype.Date    `json:"date"`
	DateDue                 pgtype.Date    `json:"date_due"`
	DocumentNumber          pgtype.Text    `json:"document_number"`
	Name                    pgtype.Text    `json:"name"`
	Memo                    pgtype.Text    `json:"memo"`
	Item                    pgtype.Text    `json:"item"`
	Qty                     pgtype.Numeric `json:"qty"`
	ContractQuantity        pgtype.Numeric `json:"contract_quantity"`
	UnitPrice               pgtype.Numeric `json:"unit_price"`
	Amount                  pgtype.Numeric `json:"amount"`
	StartDateLine           pgtype.Date    `json:"start_date_line"`
	EndDateLineLevel        pgtype.Date    `json:"end_date_line_level"`
	Account                 pgtype.Text    `json:"account"`
	SalesforceOpportunityID pgtype.Text    `json:"salesforce_opportunity_id"`
	SalesforcePricebookID   pgtype.Text    `json:"salesforce_pricebook_id"`
	ItemInternalID          pgtype.Text    `json:"item_internal_id"`
	EntityInternalID        pgtype.Text    `json:"entity_internal_id"`
	ShippingAddressCity     pgtype.Text    `json:"shipping_address_city"`
	ShippingAddressState    pgtype.Text    `json:"shipping_address_state"`
	ShippingAddressCountry  pgtype.Text    `json:"shipping_address_country"`
}

type NsSoLineItem struct {
	ID                          pgtype.UUID    `json:"id"`
	SalesforceOpportunityID     pgtype.Text    `json:"salesforce_opportunity_id"`
	SalesforceOpportunityLineID pgtype.Text    `json:"salesforce_opportunity_line_id"`
	CustomerProject             string         `json:"customer_project"`
	DocumentNumber              pgtype.Text    `json:"document_number"`
	DocumentDate                pgtype.Date    `json:"document_date"`
	StartDate                   pgtype.Date    `json:"start_date"`
	EndDate                     pgtype.Date    `json:"end_date"`
	ItemName                    pgtype.Text    `json:"item_name"`
	ItemDisplayName             pgtype.Text    `json:"item_display_name"`
	LineStartDate               pgtype.Date    `json:"line_start_date"`
	LineEndDate                 pgtype.Date    `json:"line_end_date"`
	Quantity                    pgtype.Numeric `json:"quantity"`
	ContractQuantity            pgtype.Numeric `json:"contract_quantity"`
	UnitPrice                   pgtype.Numeric `json:"unit_price"`
	TotalAmountDuePartner       pgtype.Numeric `json:"total_amount_due_partner"`
	AmountGross                 pgtype.Numeric `json:"amount_gross"`
	TermsDaysTillNetDue         pgtype.Numeric `json:"terms_days_till_net_due"`
}

type SfdcOppLineItem struct {
	ID                           pgtype.UUID    `json:"id"`
	OpportunityID                pgtype.Text    `json:"opportunity_id"`
	OpportunityProductCasesafeID pgtype.Text    `json:"opportunity_product_casesafe_id"`
	OpportunityName              pgtype.Text    `json:"opportunity_name"`
	AccountName                  pgtype.Text    `json:"account_name"`
	CloseDate                    pgtype.Date    `json:"close_date"`
	BookedDate                   pgtype.Date    `json:"booked_date"`
	FiscalPeriod                 pgtype.Text    `json:"fiscal_period"`
	PaymentSchedule              pgtype.Text    `json:"payment_schedule"`
	PaymentDue                   pgtype.Text    `json:"payment_due"`
	ContractStartDate            pgtype.Date    `json:"contract_start_date"`
	ContractEndDate              pgtype.Date    `json:"contract_end_date"`
	TermInMonthsDeprecated       pgtype.Numeric `json:"term_in_months_deprecated"`
	ProductName                  pgtype.Text    `json:"product_name"`
	DeploymentType               pgtype.Text    `json:"deployment_type"`
	Amount                       pgtype.Numeric `json:"amount"`
	Quantity                     pgtype.Numeric `json:"quantity"`
	ListPrice                    pgtype.Numeric `json:"list_price"`
	SalesPrice                   pgtype.Numeric `json:"sales_price"`
	TotalPrice                   pgtype.Numeric `json:"total_price"`
	StartDate                    pgtype.Date    `json:"start_date"`
	EndDate                      pgtype.Date    `json:"end_date"`
	TermInMonths                 pgtype.Numeric `json:"term_in_months"`
	ProductCode                  pgtype.Text    `json:"product_code"`
	TotalAmountDueCustomer       pgtype.Numeric `json:"total_amount_due_customer"`
	TotalAmountDuePartner        pgtype.Numeric `json:"total_amount_due_partner"`
	ActiveProduct                pgtype.Bool    `json:"active_product"`
}
