// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ns_invoice_sales_tax_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNsInvoiceSalesTaxItems = `-- name: InsertNsInvoiceSalesTaxItems :exec

INSERT INTO ns_invoice_sales_tax_items (
    type,
    date,
    date_due,
    document_number,
    name,
    memo,
    item,
    qty,
    contract_quantity,
    unit_price,
    amount,
    start_date_line,
    end_date_line_level,
    account,
    salesforce_opportunity_id,
    salesforce_pricebook_id,
    item_internal_id,
    entity_internal_id,
    shipping_address_city,
    shipping_address_state,
    shipping_address_country
)
values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
ON CONFLICT ON CONSTRAINT ns_invoice_sales_tax_items_all_fields_unique
DO NOTHING
`

type InsertNsInvoiceSalesTaxItemsParams struct {
	Type                    pgtype.Text    `json:"type"`
	Date                    pgtype.Date    `json:"date"`
	DateDue                 pgtype.Date    `json:"date_due"`
	DocumentNumber          pgtype.Text    `json:"document_number"`
	Name                    pgtype.Text    `json:"name"`
	Memo                    pgtype.Text    `json:"memo"`
	Item                    pgtype.Text    `json:"item"`
	Qty                     pgtype.Numeric `json:"qty"`
	ContractQuantity        pgtype.Numeric `json:"contract_quantity"`
	UnitPrice               pgtype.Numeric `json:"unit_price"`
	Amount                  pgtype.Numeric `json:"amount"`
	StartDateLine           pgtype.Date    `json:"start_date_line"`
	EndDateLineLevel        pgtype.Date    `json:"end_date_line_level"`
	Account                 pgtype.Text    `json:"account"`
	SalesforceOpportunityID pgtype.Text    `json:"salesforce_opportunity_id"`
	SalesforcePricebookID   pgtype.Text    `json:"salesforce_pricebook_id"`
	ItemInternalID          pgtype.Text    `json:"item_internal_id"`
	EntityInternalID        pgtype.Text    `json:"entity_internal_id"`
	ShippingAddressCity     pgtype.Text    `json:"shipping_address_city"`
	ShippingAddressState    pgtype.Text    `json:"shipping_address_state"`
	ShippingAddressCountry  pgtype.Text    `json:"shipping_address_country"`
}

func (q *Queries) InsertNsInvoiceSalesTaxItems(ctx context.Context, arg InsertNsInvoiceSalesTaxItemsParams) error {
	_, err := q.db.Exec(ctx, insertNsInvoiceSalesTaxItems,
		arg.Type,
		arg.Date,
		arg.DateDue,
		arg.DocumentNumber,
		arg.Name,
		arg.Memo,
		arg.Item,
		arg.Qty,
		arg.ContractQuantity,
		arg.UnitPrice,
		arg.Amount,
		arg.StartDateLine,
		arg.EndDateLineLevel,
		arg.Account,
		arg.SalesforceOpportunityID,
		arg.SalesforcePricebookID,
		arg.ItemInternalID,
		arg.EntityInternalID,
		arg.ShippingAddressCity,
		arg.ShippingAddressState,
		arg.ShippingAddressCountry,
	)
	return err
}

const removeNsInvoiceSalesTaxItems = `-- name: RemoveNsInvoiceSalesTaxItems :exec
DELETE FROM ns_invoice_sales_tax_items
WHERE
    ($1 IS NULL OR salesforce_opportunity_id = $1)
    AND
    ($2 IS NULL OR document_number = $2)
`

type RemoveNsInvoiceSalesTaxItemsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) RemoveNsInvoiceSalesTaxItems(ctx context.Context, arg RemoveNsInvoiceSalesTaxItemsParams) error {
	_, err := q.db.Exec(ctx, removeNsInvoiceSalesTaxItems, arg.Column1, arg.Column2)
	return err
}

const resetNsInvoiceSalesTaxItems = `-- name: ResetNsInvoiceSalesTaxItems :exec
DELETE FROM ns_invoice_sales_tax_items
`

func (q *Queries) ResetNsInvoiceSalesTaxItems(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetNsInvoiceSalesTaxItems)
	return err
}

const updateNsInvoiceSalesTaxItems = `-- name: UpdateNsInvoiceSalesTaxItems :one

UPDATE ns_invoice_sales_tax_items
    SET
    type = $2,
    date = $3,
    date_due = $4,
    document_number = $5,
    name = $6,
    memo = $7,
    item = $8,
    qty = $9,
    contract_quantity = $10,
    unit_price = $11,
    amount = $12,
    start_date_line = $13,
    end_date_line_level = $14,
    account = $15,
    salesforce_opportunity_id = $16,
    salesforce_pricebook_id = $17,
    item_internal_id = $18,
    entity_internal_id = $19,
    shipping_address_city = $20,
    shipping_address_state = $21,
    shipping_address_country = $22

WHERE id = $1
RETURNING id
`

type UpdateNsInvoiceSalesTaxItemsParams struct {
	ID                      pgtype.UUID    `json:"id"`
	Type                    pgtype.Text    `json:"type"`
	Date                    pgtype.Date    `json:"date"`
	DateDue                 pgtype.Date    `json:"date_due"`
	DocumentNumber          pgtype.Text    `json:"document_number"`
	Name                    pgtype.Text    `json:"name"`
	Memo                    pgtype.Text    `json:"memo"`
	Item                    pgtype.Text    `json:"item"`
	Qty                     pgtype.Numeric `json:"qty"`
	ContractQuantity        pgtype.Numeric `json:"contract_quantity"`
	UnitPrice               pgtype.Numeric `json:"unit_price"`
	Amount                  pgtype.Numeric `json:"amount"`
	StartDateLine           pgtype.Date    `json:"start_date_line"`
	EndDateLineLevel        pgtype.Date    `json:"end_date_line_level"`
	Account                 pgtype.Text    `json:"account"`
	SalesforceOpportunityID pgtype.Text    `json:"salesforce_opportunity_id"`
	SalesforcePricebookID   pgtype.Text    `json:"salesforce_pricebook_id"`
	ItemInternalID          pgtype.Text    `json:"item_internal_id"`
	EntityInternalID        pgtype.Text    `json:"entity_internal_id"`
	ShippingAddressCity     pgtype.Text    `json:"shipping_address_city"`
	ShippingAddressState    pgtype.Text    `json:"shipping_address_state"`
	ShippingAddressCountry  pgtype.Text    `json:"shipping_address_country"`
}

func (q *Queries) UpdateNsInvoiceSalesTaxItems(ctx context.Context, arg UpdateNsInvoiceSalesTaxItemsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateNsInvoiceSalesTaxItems,
		arg.ID,
		arg.Type,
		arg.Date,
		arg.DateDue,
		arg.DocumentNumber,
		arg.Name,
		arg.Memo,
		arg.Item,
		arg.Qty,
		arg.ContractQuantity,
		arg.UnitPrice,
		arg.Amount,
		arg.StartDateLine,
		arg.EndDateLineLevel,
		arg.Account,
		arg.SalesforceOpportunityID,
		arg.SalesforcePricebookID,
		arg.ItemInternalID,
		arg.EntityInternalID,
		arg.ShippingAddressCity,
		arg.ShippingAddressState,
		arg.ShippingAddressCountry,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
