// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ns_so_line_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNsSoLineItems = `-- name: InsertNsSoLineItems :exec

INSERT INTO ns_so_line_items (
    salesforce_opportunity_id,
    salesforce_opportunity_line_id,
    customer_project,
    document_number,
    document_date,
    start_date,
    end_date,
    item_name,
    item_display_name,
    line_start_date,
    line_end_date,
    quantity,
    contract_quantity,
    unit_price,
    total_amount_due_partner,
    amount_gross,
    terms_days_till_net_due
)
VALUES(
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
ON CONFLICT ON CONSTRAINT ns_so_line_items_all_fields_unique
DO NOTHING
`

type InsertNsSoLineItemsParams struct {
	SalesforceOpportunityID     pgtype.Text    `json:"salesforce_opportunity_id"`
	SalesforceOpportunityLineID pgtype.Text    `json:"salesforce_opportunity_line_id"`
	CustomerProject             string         `json:"customer_project"`
	DocumentNumber              pgtype.Text    `json:"document_number"`
	DocumentDate                pgtype.Date    `json:"document_date"`
	StartDate                   pgtype.Date    `json:"start_date"`
	EndDate                     pgtype.Date    `json:"end_date"`
	ItemName                    pgtype.Text    `json:"item_name"`
	ItemDisplayName             pgtype.Text    `json:"item_display_name"`
	LineStartDate               pgtype.Date    `json:"line_start_date"`
	LineEndDate                 pgtype.Date    `json:"line_end_date"`
	Quantity                    pgtype.Numeric `json:"quantity"`
	ContractQuantity            pgtype.Numeric `json:"contract_quantity"`
	UnitPrice                   pgtype.Numeric `json:"unit_price"`
	TotalAmountDuePartner       pgtype.Numeric `json:"total_amount_due_partner"`
	AmountGross                 pgtype.Numeric `json:"amount_gross"`
	TermsDaysTillNetDue         pgtype.Numeric `json:"terms_days_till_net_due"`
}

func (q *Queries) InsertNsSoLineItems(ctx context.Context, arg InsertNsSoLineItemsParams) error {
	_, err := q.db.Exec(ctx, insertNsSoLineItems,
		arg.SalesforceOpportunityID,
		arg.SalesforceOpportunityLineID,
		arg.CustomerProject,
		arg.DocumentNumber,
		arg.DocumentDate,
		arg.StartDate,
		arg.EndDate,
		arg.ItemName,
		arg.ItemDisplayName,
		arg.LineStartDate,
		arg.LineEndDate,
		arg.Quantity,
		arg.ContractQuantity,
		arg.UnitPrice,
		arg.TotalAmountDuePartner,
		arg.AmountGross,
		arg.TermsDaysTillNetDue,
	)
	return err
}

const removeSo = `-- name: RemoveSo :exec
DELETE FROM ns_so_line_items
WHERE
    ($1 IS NULL OR salesforce_opportunity_id = $1)
    AND
    ($2 IS NULL OR document_number = $2)
`

type RemoveSoParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) RemoveSo(ctx context.Context, arg RemoveSoParams) error {
	_, err := q.db.Exec(ctx, removeSo, arg.Column1, arg.Column2)
	return err
}

const resetNsSoLineItems = `-- name: ResetNsSoLineItems :exec
DELETE FROM ns_so_line_items
`

func (q *Queries) ResetNsSoLineItems(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetNsSoLineItems)
	return err
}

const updateNsSoLineItems = `-- name: UpdateNsSoLineItems :one

UPDATE ns_so_line_items
    SET
    salesforce_opportunity_id = $2,
    salesforce_opportunity_line_id = $3,
    customer_project = $4,
    document_number = $5,
    document_date = $6,
    start_date = $7,
    end_date = $8,
    item_name = $9,
    item_display_name = $10,
    line_start_date = $11,
    line_end_date = $12,
    quantity = $13,
    contract_quantity = $14,
    unit_price = $15,
    total_amount_due_partner = $16,
    amount_gross = $17,
    terms_days_till_net_due = $18
WHERE id = $1
RETURNING id
`

type UpdateNsSoLineItemsParams struct {
	ID                          pgtype.UUID    `json:"id"`
	SalesforceOpportunityID     pgtype.Text    `json:"salesforce_opportunity_id"`
	SalesforceOpportunityLineID pgtype.Text    `json:"salesforce_opportunity_line_id"`
	CustomerProject             string         `json:"customer_project"`
	DocumentNumber              pgtype.Text    `json:"document_number"`
	DocumentDate                pgtype.Date    `json:"document_date"`
	StartDate                   pgtype.Date    `json:"start_date"`
	EndDate                     pgtype.Date    `json:"end_date"`
	ItemName                    pgtype.Text    `json:"item_name"`
	ItemDisplayName             pgtype.Text    `json:"item_display_name"`
	LineStartDate               pgtype.Date    `json:"line_start_date"`
	LineEndDate                 pgtype.Date    `json:"line_end_date"`
	Quantity                    pgtype.Numeric `json:"quantity"`
	ContractQuantity            pgtype.Numeric `json:"contract_quantity"`
	UnitPrice                   pgtype.Numeric `json:"unit_price"`
	TotalAmountDuePartner       pgtype.Numeric `json:"total_amount_due_partner"`
	AmountGross                 pgtype.Numeric `json:"amount_gross"`
	TermsDaysTillNetDue         pgtype.Numeric `json:"terms_days_till_net_due"`
}

func (q *Queries) UpdateNsSoLineItems(ctx context.Context, arg UpdateNsSoLineItemsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateNsSoLineItems,
		arg.ID,
		arg.SalesforceOpportunityID,
		arg.SalesforceOpportunityLineID,
		arg.CustomerProject,
		arg.DocumentNumber,
		arg.DocumentDate,
		arg.StartDate,
		arg.EndDate,
		arg.ItemName,
		arg.ItemDisplayName,
		arg.LineStartDate,
		arg.LineEndDate,
		arg.Quantity,
		arg.ContractQuantity,
		arg.UnitPrice,
		arg.TotalAmountDuePartner,
		arg.AmountGross,
		arg.TermsDaysTillNetDue,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
