// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sfdc_opp_line_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSfdcOppLineItems = `-- name: InsertSfdcOppLineItems :exec
INSERT INTO sfdc_opp_line_items (
    opportunity_id,
    opportunity_product_casesafe_id,
    opportunity_name,
    account_name,
    close_date,
    booked_date,
    fiscal_period,
    payment_schedule,
    payment_due,
    contract_start_date,
    contract_end_date,
    term_in_months_deprecated,
    product_name,
    deployment_type,
    amount,
    quantity,
    list_price,
    sales_price,
    total_price,
    start_date,
    end_date,
    term_in_months,
    product_code,
    total_amount_due_customer,
    total_amount_due_partner,
    active_product
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26
)
ON CONFLICT ON CONSTRAINT sfdc_opp_line_items_all_fields_unique
DO NOTHING
`

type InsertSfdcOppLineItemsParams struct {
	OpportunityID                pgtype.Text    `json:"opportunity_id"`
	OpportunityProductCasesafeID pgtype.Text    `json:"opportunity_product_casesafe_id"`
	OpportunityName              pgtype.Text    `json:"opportunity_name"`
	AccountName                  pgtype.Text    `json:"account_name"`
	CloseDate                    pgtype.Date    `json:"close_date"`
	BookedDate                   pgtype.Date    `json:"booked_date"`
	FiscalPeriod                 pgtype.Text    `json:"fiscal_period"`
	PaymentSchedule              pgtype.Text    `json:"payment_schedule"`
	PaymentDue                   pgtype.Text    `json:"payment_due"`
	ContractStartDate            pgtype.Date    `json:"contract_start_date"`
	ContractEndDate              pgtype.Date    `json:"contract_end_date"`
	TermInMonthsDeprecated       pgtype.Numeric `json:"term_in_months_deprecated"`
	ProductName                  pgtype.Text    `json:"product_name"`
	DeploymentType               pgtype.Text    `json:"deployment_type"`
	Amount                       pgtype.Numeric `json:"amount"`
	Quantity                     pgtype.Numeric `json:"quantity"`
	ListPrice                    pgtype.Numeric `json:"list_price"`
	SalesPrice                   pgtype.Numeric `json:"sales_price"`
	TotalPrice                   pgtype.Numeric `json:"total_price"`
	StartDate                    pgtype.Date    `json:"start_date"`
	EndDate                      pgtype.Date    `json:"end_date"`
	TermInMonths                 pgtype.Numeric `json:"term_in_months"`
	ProductCode                  pgtype.Text    `json:"product_code"`
	TotalAmountDueCustomer       pgtype.Numeric `json:"total_amount_due_customer"`
	TotalAmountDuePartner        pgtype.Numeric `json:"total_amount_due_partner"`
	ActiveProduct                pgtype.Bool    `json:"active_product"`
}

func (q *Queries) InsertSfdcOppLineItems(ctx context.Context, arg InsertSfdcOppLineItemsParams) error {
	_, err := q.db.Exec(ctx, insertSfdcOppLineItems,
		arg.OpportunityID,
		arg.OpportunityProductCasesafeID,
		arg.OpportunityName,
		arg.AccountName,
		arg.CloseDate,
		arg.BookedDate,
		arg.FiscalPeriod,
		arg.PaymentSchedule,
		arg.PaymentDue,
		arg.ContractStartDate,
		arg.ContractEndDate,
		arg.TermInMonthsDeprecated,
		arg.ProductName,
		arg.DeploymentType,
		arg.Amount,
		arg.Quantity,
		arg.ListPrice,
		arg.SalesPrice,
		arg.TotalPrice,
		arg.StartDate,
		arg.EndDate,
		arg.TermInMonths,
		arg.ProductCode,
		arg.TotalAmountDueCustomer,
		arg.TotalAmountDuePartner,
		arg.ActiveProduct,
	)
	return err
}

const removeOpp = `-- name: RemoveOpp :exec
DELETE FROM sfdc_opp_line_items
WHERE opportunity_id = $1
`

func (q *Queries) RemoveOpp(ctx context.Context, opportunityID pgtype.Text) error {
	_, err := q.db.Exec(ctx, removeOpp, opportunityID)
	return err
}

const resetSfdcOppLineItems = `-- name: ResetSfdcOppLineItems :exec
DELETE FROM sfdc_opp_line_items
`

func (q *Queries) ResetSfdcOppLineItems(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetSfdcOppLineItems)
	return err
}

const updateSfdcOppLineItemById = `-- name: UpdateSfdcOppLineItemById :one
UPDATE sfdc_opp_line_items
    SET

    opportunity_id = $2,
    opportunity_product_casesafe_id = $3,
    opportunity_name = $4,
    account_name = $5,
    close_date = $6,
    booked_date = $7,
    fiscal_period = $8,
    payment_schedule = $9,
    payment_due = $10,
    contract_start_date = $11,
    contract_end_date = $12,
    term_in_months_deprecated = $13,
    product_name = $14,
    deployment_type = $15,
    amount = $16,
    quantity = $17,
    list_price = $18,
    sales_price = $19,
    total_price = $20,
    start_date = $21,
    end_date = $22,
    term_in_months = $23,
    product_code = $24,
    total_amount_due_customer = $25,
    total_amount_due_partner = $26,
    active_product = $27
WHERE id = $1
RETURNING id
`

type UpdateSfdcOppLineItemByIdParams struct {
	ID                           pgtype.UUID    `json:"id"`
	OpportunityID                pgtype.Text    `json:"opportunity_id"`
	OpportunityProductCasesafeID pgtype.Text    `json:"opportunity_product_casesafe_id"`
	OpportunityName              pgtype.Text    `json:"opportunity_name"`
	AccountName                  pgtype.Text    `json:"account_name"`
	CloseDate                    pgtype.Date    `json:"close_date"`
	BookedDate                   pgtype.Date    `json:"booked_date"`
	FiscalPeriod                 pgtype.Text    `json:"fiscal_period"`
	PaymentSchedule              pgtype.Text    `json:"payment_schedule"`
	PaymentDue                   pgtype.Text    `json:"payment_due"`
	ContractStartDate            pgtype.Date    `json:"contract_start_date"`
	ContractEndDate              pgtype.Date    `json:"contract_end_date"`
	TermInMonthsDeprecated       pgtype.Numeric `json:"term_in_months_deprecated"`
	ProductName                  pgtype.Text    `json:"product_name"`
	DeploymentType               pgtype.Text    `json:"deployment_type"`
	Amount                       pgtype.Numeric `json:"amount"`
	Quantity                     pgtype.Numeric `json:"quantity"`
	ListPrice                    pgtype.Numeric `json:"list_price"`
	SalesPrice                   pgtype.Numeric `json:"sales_price"`
	TotalPrice                   pgtype.Numeric `json:"total_price"`
	StartDate                    pgtype.Date    `json:"start_date"`
	EndDate                      pgtype.Date    `json:"end_date"`
	TermInMonths                 pgtype.Numeric `json:"term_in_months"`
	ProductCode                  pgtype.Text    `json:"product_code"`
	TotalAmountDueCustomer       pgtype.Numeric `json:"total_amount_due_customer"`
	TotalAmountDuePartner        pgtype.Numeric `json:"total_amount_due_partner"`
	ActiveProduct                pgtype.Bool    `json:"active_product"`
}

func (q *Queries) UpdateSfdcOppLineItemById(ctx context.Context, arg UpdateSfdcOppLineItemByIdParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateSfdcOppLineItemById,
		arg.ID,
		arg.OpportunityID,
		arg.OpportunityProductCasesafeID,
		arg.OpportunityName,
		arg.AccountName,
		arg.CloseDate,
		arg.BookedDate,
		arg.FiscalPeriod,
		arg.PaymentSchedule,
		arg.PaymentDue,
		arg.ContractStartDate,
		arg.ContractEndDate,
		arg.TermInMonthsDeprecated,
		arg.ProductName,
		arg.DeploymentType,
		arg.Amount,
		arg.Quantity,
		arg.ListPrice,
		arg.SalesPrice,
		arg.TotalPrice,
		arg.StartDate,
		arg.EndDate,
		arg.TermInMonths,
		arg.ProductCode,
		arg.TotalAmountDueCustomer,
		arg.TotalAmountDuePartner,
		arg.ActiveProduct,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
